<h2>Crud Phalcon Sederhana</h2>

<p><?php echo $this->flashSession->output() ?></p>

<?php echo $this->tag->form("profile/register") ?>

    <div class="form-group">
        <label for="name">Name</label>
        <?php echo $this->tag->textField(["name", "class" => "form-control", "placeholder" => "Enter Fullname"]); ?>
    </div>

    <div class="form-group"> 
        <label for="email">Email</label>
        <?php echo $this->tag->emailField(["email", "class" => "form-control", "placeholder" => "Enter Fullname"]); ?>
    </p>

    <div class="form-group">
        <?php echo $this->tag->submitButton(["Register", "class" => "btn btn-primary"]) ?>
    </p>

</form>

<?php 

if ($users->count() > 0) {
    ?>
    <table class="table table-bordered table-hover">
        <thead class="thead-light">
        <tr>
            <th>#</th>
            <th>Name</th>
            <th>Email</th>
            <th>Action</th>
        </tr>
        </thead>
        <tfoot>
        <tr>
            <td colspan="4">Users quantity: <?php echo $users->count(); ?></td>
        </tr>
        </tfoot>
        <tbody>
        <?php foreach ($users as $user) { ?>
            <tr>
                <td><?php echo $user->id; ?></td>
                <td><?php echo $user->name; ?></td>
                <td><?php echo $user->email; ?></td>
                <td>
                    <?php
                        echo $this->tag->linkTo([
                            "profile/edit/".$user->id,
                            '<i class="fa fa-pencil"></i>',
                            "class" => "btn btn-primary", 
                            "title" => "Edit Article"
                        ]);
                    ?>

                    <?php
                        echo $this->tag->linkTo([
                            "profile/delete/".$user->id,
                            '<i class="fa fa-trash"></i>',
                            "class" => "btn btn-danger", 
                            "title" => "Edit Article"
                        ]);
                    ?>
                </td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
    <?php
}